# Generated by Django 6.0.4 on 2026-04-26 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_view_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='view_once_consumed_by',
            field=models.ManyToManyField(blank=True, related_name='consumed_view_once_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
