# Generated by Django 6.0.4 on 2026-04-26 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_view_once_message_view_once_consumed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset', models.CharField(choices=[('default', 'Default'), ('light', 'Light'), ('dark', 'Dark'), ('gradient_blue', 'Blue Gradient'), ('gradient_sunset', 'Sunset Gradient'), ('gradient_aurora', 'Aurora Gradient'), ('solid', 'Solid Color'), ('image', 'Custom Image')], default='default', max_length=20)),
                ('bg_color', models.CharField(blank=True, max_length=32)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='chat_themes/')),
                ('bubble_me_color', models.CharField(blank=True, max_length=32)),
                ('bubble_other_color', models.CharField(blank=True, max_length=32)),
                ('text_color', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation_theme',
                'indexes': [models.Index(fields=['user', 'conversation'], name='chat_conver_user_id_14a56b_idx')],
                'unique_together': {('user', 'conversation')},
            },
        ),
    ]
