# Generated by Django 6.0.4 on 2026-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversationtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_photo_swap',
            field=models.BooleanField(default=False),
        ),
    ]
