# Generated by Django 6.0.4 on 2026-04-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_photo_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo_swap_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Admin verification status for PhotoSwap media', max_length=10),
        ),
    ]
