# Generated by Django 6.0.4 on 2026-04-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_photo_swap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo_swap_response_to',
            field=models.ForeignKey(blank=True, help_text='Links a response message to the original PhotoSwap message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_swap_responses', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo_swap_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='PhotoSwap state: active=waiting for response, pending=admin review, approved=revealed, rejected=blocked', max_length=10),
        ),
    ]
